#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require_once __DIR__.'/vendor/autoload.php';
} elseif (file_exists(__DIR__.'/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
} else {
    require_once 'phar://robo.phar/vendor/autoload.php';
}

$runner = new \Robo\Runner();
$runner->execute();
